### ISSUE TITLE
Tag for last commits

### ISSUE THREAD

**Issue by jb-reynaud** [PolishSymfonyCommunity/Symfony2MockerExtension#10]
Hi,

Is it possible to have a tag version for using your last works since last tag v1.0.2, as I prefer to use a tag version rather than dev-master in my composer.json

thanks!

**Comment by jakzal** [comment]
@jibe84 a tagged but unstable release will make you feel better than using dev-master? ;)  tagging doesn't make things stable.

**Comment by jibe84** [comment]
Well it's more if you decide to change everything and I make a composer update on my project and break everything ;) anyway I'm going to use dev-master#commit-hash.

**Comment by jakzal** [comment]
@jibe84 a new release was tagged
