### ISSUE TITLE
Documentation link on the README does not work

### ISSUE THREAD

**Issue by eddiejaoude** [PolishSymfonyCommunity/Symfony2MockerExtension#7]
http://extensions.behat.org/symfony2-mocker/

**Comment by jakzal** [comment]
Unfortunately the new behat extensions page is not ready yet, so all the Behat2 extension doc links are now broken. You'll find the docs in https://github.com/PolishSymfonyCommunity/Symfony2MockerExtension/tree/master/doc.

**Comment by eddiejaoude** [comment]
Thanks.
